# Generated by Django 5.1.1 on 2024-09-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('codCliente', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nomeCliente', models.CharField(max_length=30)),
                ('telefoneCliente', models.CharField(max_length=12)),
            ],
        ),
    ]
