# Generated by Django 5.1.1 on 2024-09-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gacbase', '0002_prestador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('codProduto', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('descProduto', models.CharField(max_length=30)),
                ('precoUnitarioProduto', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
    ]
