# Generated by Django 5.1.1 on 2024-09-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gacbase', '0004_alter_prestador_statusprestador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestador',
            name='statusPrestador',
            field=models.BooleanField(default=False),
        ),
    ]
