# Generated by Django 5.1.1 on 2024-09-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gacbase', '0005_alter_prestador_statusprestador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('codProduto', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('estoqueProduto', models.IntegerField(default=0, max_length=5)),
            ],
        ),
    ]
