# Generated by Django 5.1.1 on 2024-09-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gacbase', '0007_alter_estoque_estoqueproduto'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='unidadeProduto',
            field=models.CharField(default='UND', max_length=3),
        ),
    ]
