# Generated by Django 5.1.1 on 2024-09-17 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gacbase', '0008_estoque_unidadeproduto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('codPedido', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('qtdProduto', models.IntegerField(default=0)),
                ('valorConsumido', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('estadoPedido', models.BooleanField(default=False)),
                ('codPrestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gacbase.prestador')),
                ('codProduto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gacbase.produto')),
            ],
        ),
    ]
