# Generated by Django 5.1.1 on 2024-09-18 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gacbase', '0009_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamentos',
            fields=[
                ('codPagamento', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('formaPagamento', models.CharField(max_length=10)),
                ('totalPagamento', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('descontoPagamento', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('valorPagamento', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('codPedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gacbase.pedido')),
            ],
        ),
    ]
