# Generated by Django 5.1.1 on 2024-09-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gacbase', '0010_pagamentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamentos',
            name='formaPagamento',
            field=models.CharField(choices=[('debito', 'Debito'), ('credito', 'Credito'), ('pix', 'PIX'), ('dinheiro', 'Dinheiro'), ('promo', 'Promocao'), ('pdp', 'PDP')], max_length=10),
        ),
    ]
