# Generated by Django 5.1.1 on 2024-09-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gacbase', '0011_alter_pagamentos_formapagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestador',
            name='statusPrestador',
            field=models.BooleanField(choices=[('aberto', 'Aberto'), ('fechado', 'Fechado')], default=False),
        ),
    ]
